# 生产环境配置文件
spring:
  application:
    name: geekoj-backend-gateway
server:
  port: 8100
geekoj:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  base:
    url: ${BACKEND_URL:http://localhost:8100}
  nacos:
    host: ${NACOS_HOST:localhost}
    port: ${NACOS_PORT:8848}
    username: ${NACOS_USERNAME:nacos}
    password: ${NACOS_PASSWORD:nacos}
  sentinel:
    host: ${SENTINEL_HOST:localhost}
    port: ${SENTINEL_PORT:8858}
  redis:
    database: ${REDIS_DATABASE:0}
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123456}
knife4j:
  gateway:
    enabled: false
system:
  security:
    check-disabled-apis: true
    disabled-apis:
      - /api/user/register
      - /api/user/loginByPhone
      - /api/user/sms/sendCode
      - /api/user/email/sendCode
      - /api/user/update
      - /api/user/pwd
      - /api/user/phone
      - /api/user/email
      - /api/user/tags/add
      - /api/user/oss/policy
      - /api/user/oauth2.0/gitee/success
