spring:
  profiles:
    active: ${geekoj.profiles.active}
  main:
    web-application-type: reactive
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        enabled: true
      server-addr: ${geekoj.nacos.host}:${geekoj.nacos.port}
      username: ${geekoj.nacos.username}
      password: ${geekoj.nacos.password}
    sentinel:
      eager: true
      transport:
        dashboard: ${geekoj.sentinel.host}:${geekoj.sentinel.port}
    gateway:
      routes:
        - id: geekoj-backend-user-service
          uri: lb://geekoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: geekoj-backend-question-service
          uri: lb://geekoj-backend-question-service
          predicates:
            - Path=/api/oj/**
        - id: geekoj-backend-judge-service
          uri: lb://geekoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  data:
    redis:
      database: ${geekoj.redis.database}
      host: ${geekoj.redis.host}
      port: ${geekoj.redis.port}
      password: ${geekoj.redis.password}
      timeout: 5000
      lettuce:
        pool:
          enabled: true
          max-active: 200
          max-wait: -1ms
          max-idle: 50
          min-idle: 0
cors:
  allowed-origin: ${geekoj.base.url}
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-headers: content-type, x-requested-with, sa-token, *
  max-age: 3600
system:
  security:
    no-auth-apis:
      - /api/user
      - /api/user/info
      - /api/user/register
      - /api/user/login
      - /api/user/loginByPhone
      - /api/user/sms/sendCode
      - /api/user/email/sendCode
      - /api/user/oauth2.0/gitee/success
      - /api/oj/question/page/vo/safe
      - /api/oj/question/tags
      - /api/oj/question_submit/page/vo
      - /api/oj/question_submit/summary