# 开发环境配置文件
spring:
  application:
    name: geekoj-backend-question-service
server:
  port: 8102
geekoj:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  base:
    url: ${BACKEND_URL:http://localhost:8100}
  mysql:
    database: ${MYSQL_DATABASE:geekoj_cloud}
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
  nacos:
    host: ${NACOS_HOST:localhost}
    port: ${NACOS_PORT:8848}
    username: ${NACOS_USERNAME:nacos}
    password: ${NACOS_PASSWORD:nacos}
  sentinel:
    host: ${SENTINEL_HOST:localhost}
    port: ${SENTINEL_PORT:8858}
  redis:
    database: ${REDIS_DATABASE:0}
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123456}
  rocketmq:
    host: ${ROCKETMQ_HOST:localhost}
    port: ${ROCKETMQ_PORT:9876}
    group: ${ROCKETMQ_GROUP:geekoj}
  dubbo:
    port: ${DUBBO_PORT:-1}