# 公共配置文件
spring:
  application:
    name: geekoj-backend-question-service
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
  freemarker:
    enabled: false
    check-template-location: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://link:3306/geekoj
    username: root
    password: ytz
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # Redis 配置
  data:
    redis:
      database: 2
      host: link
      port: 6379
      timeout: 5000
      password: geektip
  cloud:
    nacos:
      discovery:
        enabled: true
      server-addr: link:8848
      username: nacos
      password: nacos
dubbo:
  application:
    name: GeekOJ
    version: 1.0.0
  registry:
    address: nacos://link:8848?username=nacos&password=nacos
  protocol:
    name: dubbo
    port: 20802
  scan:
    base-packages: cc.geektip.geekoj.api
server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api/question
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
sa-token:
  # 打开 RPC 调用鉴权
  check-same-token: true
  is-log: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 新版本3.0接口文档配置
springdoc:
  info:
    title: "GeekOJ 问题服务"
    version: "1.0.0"
    description: "GeekOJ 问题服务接口文档"
    contact:
      name: Fish
      email: contact@geektip.cc
      url: https://oj.geektip.cc
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: "cc.geektip.geekoj.questionservice.controller"
knife4j:
  enable: true
  setting:
    language: zh_cn