# 公共配置文件
spring:
  application:
    name: geekoj-backend-user-service
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
  freemarker:
    enabled: false
    check-template-location: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://link:3306/geekoj
    username: root
    password: ytz
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # Redis 配置
  data:
    redis:
      database: 2
      host: link
      port: 6379
      timeout: 5000
      password: geektip
  cloud:
    nacos:
      discovery:
        enabled: true
      server-addr: link:8848
      username: nacos
      password: nacos
dubbo:
  application:
    name: GeekOJ
    version: 1.0.0
  registry:
    address: nacos://link:8848?username=nacos&password=nacos
  protocol:
    name: dubbo
    port: 20801
  scan:
    base-packages: cc.geektip.geekoj.api
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api/user
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
sa-token:
  # 打开 RPC 调用鉴权
  check-same-token: true
  is-log: true

# 新版本3.0接口文档配置
springdoc:
  group-configs:
    - group: "GeekOJ 用户服务"
      packages-to-scan: "cc.geektip.geekoj.userservice.controller"
knife4j:
  enable: true
  setting:
    language: zh_cn